# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Checkmarx CxFlow Action
      # You may pin to the exact commit or the version.
      # uses: checkmarx-ts/checkmarx-cxflow-github-action@fe2a395cbbee31268470d92b6c53ebc483005f0f
      uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.1
      with:
        # Provide Checkmarx URL
        checkmarx_url: # default is 
        # Select a Checkmarx Team
        team: # default is /CxServer/SP/Company
        # Provide Checkmarx Username
        checkmarx_username: # default is 
        # Provide Checkmarx Password
        checkmarx_password: # default is 
        # Provide Checkmarx Client Secret
        checkmarx_client_secret: # default is 
        # Select a Checkmarx Project
        project: # default is 
        # Select an Application Name used by downstream bug tracker systems
        app: # optional, default is SampleApp
        # Select a Checkmarx Preset
        preset: # optional, default is Checkmarx Default
        # Break build based on Checkmarx findings?
        break_build: # optional
        # Bug tracker for the scan results.
        bug_tracker: # optional, default is Sarif
        # Incremental Scans?
        incremental: # optional, default is true
        # Additional CLI parameters
        params: # optional, default is 
        # GitHub API Token
        github_token: # optional, default is ${{ github.token }}
        # Vulnerability Scanners (sast, sca, ast, cxgo)
        scanners: # default is 
        # Provide SCA API URL
        sca_api_url: # optional, default is https://api.scacheckmarx.com
        # Provide SCA APP URL
        sca_app_url: # optional, default is https://sca.scacheckmarx.com
        # Provide SCA Access Control URL
        sca_access_control_url: # optional, default is https://platform.checkmarx.net
        # Provide SCA Tenant
        sca_tenant: # optional, default is 
        # Provide SCA Username
        sca_username: # optional, default is 
        # Provide SCA Password
        sca_password: # optional, default is 
        # Provide CxGo Client Secret
        cxgo_client_secret: # optional, default is 
        # Provide CxGo API URL
        cxgo_base_url: # optional, default is https://api.checkmarx.net
        # Provide CxGo Portal URL
        cxgo_portal_url: # optional, default is https://cloud.checkmarx.net
        # Provide AST API URL
        ast_api_url: # optional, default is 
        # Provide AST WebApp URL
        ast_webapp_url: # optional, default is 
        # Provide AST Client ID
        ast_client_id: # optional, default is 
        # Provide AST Client Secret
        ast_client_secret: # optional, default is 
